[api][dist] Update peek-mysql2 gem
Previous version of peek-mysql2 was using alias_method_chain. That
method got dropped in rails 5.1.

To solve this we had to upgrade peek-mysql2.

====

Bundler::GemRequireError: There was an error while trying to load the gem 'peek-mysql2'.
Gem Load Error is: undefined method `alias_method_chain' for Mysql2::Client:Class
Did you mean?  alias_method