[api][dist] Update haml_lint gem
Previous version caused some errors after upgrading to Rails 5.
This gets solved with version 0.26 of haml_lint.

The upgrade introduced 2 new haml lint cops, which we disabled
for now.

===

undefined method `each' for nil:NilClass
/usr/lib64/ruby/gems/2.4.0/gems/haml_lint-0.24.0/lib/haml_lint/linter/class_attribute_with_static_value.rb:33:in `contains_class_attribute?'
/usr/lib64/ruby/gems/2.4.0/gems/haml_lint-0.24.0/lib/haml_lint/linter/class_attribute_with_static_value.rb:24:in